# The URL the site will be built for
base_url = "https://sydneyjacoby.com"

title = "Sydney Jacoby | MSN, RN"
description = "IDK some fucking lady"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

theme = "ntun"
default_language = "en"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
author = "Sydney Jacoby"
author_image="android-chrome-512x512.png"
about_title = "About Me"
city="New York"
years="2022"

job = "Doctor Bitch"
description = "Weed Smoker Extraordinaire"

links = [
    { url = "", title="", icon = "fab fa-instagram"},
    { url = "", title="", icon = "fab fa-twitter"},
    { url = "https://www.linkedin.com/in/sydney-jacoby", title="LinkedIn", icon = "fab fa-linkedin"},
    { url = "mailto:jacobysydney@yahoo.com", title="Email", icon = "fas fa-envelope"}
]